index.js, test/mock_adapter_test.js
If i return a status code like 401 from my mocked service, i'd expect the call to axios to be rejected, as it is in both the http and the xhr adapter. Agreed?
Test is ugly because there are no spies in mocha and i didnt wanna add a dependency. hope that's still okeydokey
=> reject bad http status codes

index.js, test/mock_adapter_test.js
I was getting `TypeError: Cannot read property 'find' of undefined` because my method was all caps.
=> GET vs get - Accept method in any case when passing the relevant config to axios.

package.json, src/index.js
There are breaking changes in `axios@0.13.0` related to request adapters. This PR addresses those changes. For further details see [Upgrade Guide](https://github.com/mzabriskie/axios/blob/master/UPGRADE_GUIDE.md#012x---0130).
=> Updating to axios@0.13.0

README.md, package.json, src/index.js, src/utils.js, test/basics.spec.js, test/on_any.spec.js, test/reply_once.spec.js
fixes #10 
I used JSON.stringify for comparison, since the request body/data in the axios request config is a JSON string anyway, so no dependency added.
Since I didn't add filtering to only allow post/put/patch for this other types (get etc) will not match a request handler with a body.
All tests and linting are green on my machine.
=> added request body/data matching

README.md, package.json, src/handle_request.js, src/index.js, test/pass_through.spec.js, test/promise.spec.js
Resolves #19 and #20: 
* Use `passThrough: true` to route non-mocked endpoints back to Axios
* Add support for `.reply(function)` itself returning a Promise
I put a note in README.md that support for replying with a Promise will come out in version 1.7.0. Please edit if next version is not that.
=> Implement passThrough and reply() with Promise

README.md, src/handle_request.js, src/index.js, src/utils.js, test/basics.spec.js, test/pass_through.spec.js
As discussed in #21, a more suitable approach for the `passThrough` behaviour is to implement it as a specific kind of handler. This PR does that, and also adds support for matching all paths (i.e. `/.*/`) when no path is specified.
Note: I needed to change the format of the internal handler specification. This caused two tests in the "basic" set to fail. Since the internal formats are anyway not part of the documented API, I thought better to just remove those tests as the functionality is anyway covered by other tests.
=> passThrough refactoring

src/utils.js, test/basics.spec.js
When you have more than one request to the server in some test, it would be very helpful to see which one request was failed.
=> report url in the error message

src/handle_request.js, src/index.js
Hi, I did a "quick and dirty" fix for #35 by passing the stored `originalAdapter` back to axios in case of a passThrough. It solved my problem and it passes all the tests, but you might want to check if this approach is the most correct.
Thanks,
danii
=> Passthrough issue35

src/handle_request.js, src/utils.js, test/basics.spec.js
Let's say I have code like:
```javascript
var buffer = new ArrayBuffer(1);
var view = new Uint8Array(buffer);
view[0] = 0xAA;
mock.onGet('/some-url').reply(200, buffer);
axios({
url: '/some-url',
method: 'GET',
responseType: 'arraybuffer'
}).then(function(response) {
response.data;  // <-- HERE response.data is not a ArrayBuffer, but an empty object `{}`
});
```
So, I can't mock for example image generator.
I've changed a check `isObject` to be way more stricter thus allowing blobs, buffers, files to no be wrapped and unwrapped with JSON converter.
I've created a test, but I've not updated documentation since my English is quite bad.
=> Feature Request: `reply` can't replay with ArrayBuffer, Blob, etc. responses

src/utils.js, test/basics.spec.js
In my company we wanted to check params for delete request, which is allowed by axios, so mock also should support it.
Now it would check only params if they exists.
=> Check params if they exist

src/index.js
This pr allows you to do: `import AxiosMockAdapter from 'axios-mock-adapter';` in Typescript.
cc:
@tkryskiewicz
=> feature(index.js): export default class for use in typescript.

src/index.js, test/basics.spec.js
This PR is to allow `OPTIONS` [preflighted requests ](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Preflighted_requests) which is used to check if we are allowed to perform HTTP requests across different domains.
=> Add options verb support

src/index.js, types/index.d.ts, types/test.ts
Currently default import is not working in typescript
This should fix it and enable importing adapter as
```
import MockAdapter from "axios-mock-adapter";
```
=> Use default import in typescript

src/handle_request.js, src/utils.js, test/basics.spec.js
This adds support for the use case defined in #74, a matcher on the concatenation of `config.baseURL` and `config.url`. In other words, the following will be supported where it wasn't before:
```js
const axios = require('axios');
const MockAdapter = require('axios-mock-adapter');
const mock = new MockAdapter(axios);
mock.onGet('/api/v1/test').reply(200);
const reqOptions = {
method: 'GET',
baseURL: '/api/v1',
url: '/test',
};
axios(reqOptions).then((response) => {
console.log(response.status); // => 200
});
```
=> add support for matchers on the concatenation of the baseURL and url properties (fixes #74)

src/index.js, test/basics.spec.js
Ran into the following situation:
```
mock.onGet('/').reply(200);
mock.onGet('/').reply(500);
axios.get('/).then(() => console.log('then')).catch(err => console.log(err))
```
.catch will be called as handlers.get array now has 2 mocks for the same endpoint but we iterate from the top down never hitting the second. 
This PR will check to see if a `handler` exist on a `method`, if so it will replace the existing handler with the new handler.
The reason I created this PR is that I am using axios-mock-adapter to set up my initial mocks across all of my endpoints (for local development without having to VPN into our network). When I go to test a different response/status on x endpoint it defaults to the initial calls. I tried to use replyOnce but that gave weird results as the webapp makes …
=> Existing mock should be overwritten when new mock is defined

src/index.js
This allows extending of the default MockAdapter adapter
There's already the `MockAdapter.prototype.adapter = adapter;` line, so this just takes advantage of that
=> Use the adapter on the MockAdapter instance

src/handle_request.js, src/index.js, src/utils.js, test/basics.spec.js
NOTE: I closed out #114 as I feel this is a better/easier way of handling this. I removed the replyOnceHandlers as that made it super complicated for overwriting mocks. Now the replyOnce function will pass an array that has a length of 7 to addHandler. This allows us to check to see if a handler is a replyOnce handler or not. The following text is from PR #114.
I believe this will fix the issues from PR #109 as well as a different bug from #109 where mocks were getting added way too many times due to a forEach loop. With 25 onGet mocks being called with different paths and using .reply() my mock.handlers.get.length was 16,777,216.
Let me know if you have any other test that I should verify before this gets merged in or any code I can clean up
=> Investigating new handlers structure

src/handle_request.js, src/index.js, test/basics.spec.js, test/history.spec.js
This modification records each interaction with mock axios, so that a user can write tests which verify a particular call was made. For example, the code under test may make a POST, and perhaps does not do anything with the data that is returned. By checking the history of the mock interactions, a user could write a test which confirms that POST was made.
Unit tests were also written for this new functionality.
=> Implemented history to record all calls to the mock

src/handle_request.js, test/basics.spec.js
I found that if I have an interceptor that was attempting to retry a request (perhaps an interceptor that checks for 401 response codes, then requests a new oauth2 token, then retries the request) it wouldn't use the mock adapter for the retried attempts. I found that in the handle request, we setting the adapter to null. Instead we should actually delete the adapter so axios will use the instance default one.
Looks like this is also the same scenario as issue #68. Essentially any time we tried to retry a request in an interceptor using the same config, it was bypassing the mock adapter and making a real request which is why in Issue #68 they were seeing it give a 404 response code back.
=> support for mocks when an interceptor retries a request

src/handle_request.js
This keeps the URL consistent with what axios outputs by default.
When you have `baseURL` set in your default configuration, this library [strips it out of the `config.url` property](https://github.com/ctimmerm/axios-mock-adapter/blob/master/src/handle_request.js#L16) returned by the response.  This is inconsistent with the behavior of axios, which contains the fully qualified URL.
This causes libraries like `axios-cookiejar-support` to stop working because the cookie domain is validated against the domain parsed from this property.
See a reproduction of the issue here:
https://runkit.com/szdc/5b249bb0d0d7790012fc868d
=> fix: use a local variable instead of modifying config.url

src/index.js
There are some services that expose an HTTP API that use the unofficial verb 'LIST' (e.g. HashiCorp Vault).  Testing integration with these services is currently impossible with this library.  While LIST is an unofficial HTTP verb, I don't see any reason to not include it so that consumers of axios-mock-adapter can use it everywhere they need to.
=> Add list as an http verb

README.md, src/handle_request.js, test/basics.spec.js
This PR adds the ability to return an axios request in a `reply` callback function, essentially mocking a redirect:
```javascript
mock
.onGet('/bar').reply(200, { foo: 'bar' })
.onGet('/foo').reply(function() {
return axios.get('/bar')
});
axios.get('/foo')
.then(function(response) {
console.log(response.data); // { foo: 'bar' }
console.log(response.config.url); // "/bar"
});
```
This closes #145.
=> Implement redirect mocking

types/index.d.ts
The history feature isn't available for type script users at the moment.
I added the history attribute to the typescript definition.
=> Add history to typescript definition

README.md
I needed to reset history only and keep the registered mock handlers. It was missing in the docs and I was going to work on this feature. Turns out is already there inside `reset` but `README` doesn't have it. This PR Closes #190
=> Update README with info about reset methods

types/index.d.ts
=> fix: declare resetHistory method in MockAdapter class

types/index.d.ts, types/test.ts
The `mock.resetHandlers` and `mock.resetHistory` properties were missing from the type definitions. This PR adds them!
=> Add resetHandlers and resetHistory types

types/index.d.ts
... so they are more aligned with [reality](https://github.com/ctimmerm/axios-mock-adapter/blob/8681af9c8375be4c5dc798f68a90154b5552cadd/src/index.js)
=>  Fix timeout, timeoutOnce, networkError, networkErrorOnce TS typedefs

src/handle_request.js
Calling request in passThrough causes interceptor to excute twice
=> 【bugfix】call originalAdapter instead of request in passThrough

types/index.d.ts
Changed the type of `data` in `ResponseSpecFunc` to `<T = any>`.
With this change, guarantees the type of `data`.
=> change any to generic type variable

src/index.js, src/utils.js, test/basics.spec.js, test/network_error.spec.js, test/timeout.spec.js
See https://github.com/axios/axios/pull/1419
=> Set isAxiosError property on errors.

types/index.d.ts
Options was already specified in src VERBS but not defined in Types #239
=> Add Options handler

README.md, src/utils.js, test/asymmetric.spec.js
Instead of requiring an exact match, we can now also allow a partial match when using a matcher. The only requirement for such a matcher is that it has a `asymmetricMatch` method, which is the case for certain Jest and Jasmine matchers.
An example using a Jest matcher;
```js
mock.onPost(
'http://foobar.com/baz',
{ user_id: 10 },
expect.objectContaining({
'Content-Type': 'application/json',
'test-header': 'test',
})
).reply(200, { foo: 'bar' });
```
But it also is possible to create a custom matcher:
```js
mock.onPost(
'http://foobar.com/baz',
{ user_id: 10 },
{
asymmetricMatch(actual) {
return actual['some-header'] === 'foobar';
}
}
).reply(200, { foo: 'bar' });
```
Fixes #180
=> add support for asymmetric matchers

src/index.js, test/request_aborted.spec.js
This PR implement mock function that returns `Request aborted` error. Its error is called in https://github.com/axios/axios/blob/dc4bc49673943e35280e5df831f5c3d0347a9393/lib/adapters/xhr.js#L73 .
=> Implement requestAborted function

README.md, package.json, src/handle_request.js, src/index.js, test/pass_through_by_default.spec.js, test/pass_through_on_no_match.spec.js, types/index.d.ts, types/test.ts, yarn.lock
This merge request solves problem from #217
I added `onNoMatch` option to MockAdapter constructor. If you set `onNoMatch` option to `passthrough` all requests would be forwarded over network by default
```js
// Mock all requests to /foo with HTTP 200, but forward
// any others requests to server
var mock = new MockAdapter(axiosInstance, { onNoMatch: 'passthrough' });
mock
.onAny('/foo').reply(200);
```
Also i added new **bundlesize** check in testing pipeline. It checks size of minified bundle on each `yarn test` run.
=> Add onNoMatch option

src/utils.js
fix toString.call not working in IE11
https://github.com/ctimmerm/axios-mock-adapter/issues/260
=> fix for IE11

README.md, src/handle_request.js, src/utils.js, test/throw_exception_on_no_match.js
This submission allows the new option `throwException` in `onNoMatch` instance configuration.
**Current problem:**
When a request has no configured mock, is not possible to trace and identify the source of request. 
This is the only one feedback received from axios-mock-adapter:
```bash
Request failed with status code 404
at createAxiosError (node_modules/axios-mock-adapter/src/utils.js:144:19)
at Object.settle (node_modules/axios-mock-adapter/src/utils.js:124:22)
at handleRequest (node_modules/axios-mock-adapter/src/handle_request.js:127:15)
```
**Proposed solution**
Using `onNoMatch` option with `throwException` to throw an exception with details about request url and method when a request is made without match any handler.
This is the new console output:
```bash
Could not find mock …
```
=> Create onNoMatch=throwException option to throw exception when could not find mock for requested url

src/handle_request.js, test/pass_through.spec.js
I'm dealing with a 3rd party library that uses Axios and only defines `baseURL` without `url` for some reason. This results in an error because the request handler tries to call `substr` on `undefined`.
I simply added a fallback to an empty string for the `url` and added a test for it.
=> Handle request with undefined url

README.md
When utilizing the `params` option in the mock handlers, it is unclear that you need to specify _all_ key/value pairs passed to that option. Based on the current docs, it can easily be misconstrued that only the key/value pairs that you pass to the mock handler are checked for equivalency.
This update adds an additional line to the README that clarifies this behavior.
=> Clarify params usage

src/handle_request.js, test/basics.spec.js
The case of `responseURL` is incorrect; "URL" is always uppercased. See https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseURL .
=> fix responseURL case

types/index.d.ts
It looks like this was added as an option and included in the documentation but didn't get added to the types.
=> Add onNoMatch: "throwException" to types

src/index.js, test/basics.spec.js
Hey there!  This is my first public PR so if I need to change anything please let me know!  I was using this library for a project and ran into an issue when we accidentally attempted to instantiate a mock instance against an empty import.  Hopefully this saves some folks some time in the future.
• Throw an error if there is no axios instance available to mock
• Test failing constructor
=> feat(hardening): ensure that an instance is provided to mock

package-lock.json, package.json, src/handle_request.js, src/utils.js, test/utils.spec.js
This fixes #275, allowing to return Blob data in a response, and mocking any `AxiosRespones<Blob>` endpoint.
Added tests only for false-positive checking as Blob is not available in nodejs enviroment, to add missing test like 
```js
it("returns true for Blob", function () {
expect(isObjectOrArray(new Blob(['TEST BLOB'], { type: 'text/plain' }))).to.be.true;
});
```
it would be necessary to install `cross-blob` lib, but I think it is out of the scope of this fix
=> Allow Blob Responses

src/utils.js, test/basics.spec.js
I've observed some issue where non-200 responses got rejected with an error object instead of an error instance. This was caused by the current `settle` implementation, which didn't support the `validateStatus` config completely.
I've also removed support for axios < 0.16 as all the tests were failing with it and it's not worth to fix them.
Axios 0.19 got released 5 years ago. Maybe we could also drop older versions as they aren't tested.
- Officially drop support for axios < 0.16 as most of the tests were failing
- Properly support `validateStatus: null` according to the documentation of axios
=> Support for validateStatus: null

README.md
I'm surprised the existing regex even compiles but it looks like it does, and I guess it is technically a legal regex, it just will never match anything, because it requires the beginning of a string (or line) to come after a forward slash.
I'm assuming the intent was to match `/api` at the beginning of the path, so I've adjusted it accordingly.
=> Fix regex in example

src/index.js, test/basics.spec.js, test/on_any.spec.js, types/index.d.ts, types/test.ts
A while ago I had to write tests that mock an external API that uses HTTP `LINK` and `UNLINK` methods. However there was no support in axios for these methods so I added it.
To proof that these methods are a thing here is a link to an [ietf.org document](https://datatracker.ietf.org/doc/html/draft-snell-link-method).
=> added support for HTTP LINK and UNLINK

src/utils.js
From v0.27.2 axios uses a constructor to create instances of AxiosError. (See https://github.com/axios/axios/pull/3645). This PR uses said constructor to create errors and falls back to the previous behavior for older versions if the constructor is not available. This also fixes #338
=> Use AxiosError constructor to create axios errors if available

src/handle_request.js, src/index.js, test/pass_through.spec.js, test/pass_through_on_no_match.spec.js
Fixes https://github.com/ctimmerm/axios-mock-adapter/issues/357
=> Fix passthrough support with axios 1.2

types/index.d.ts, types/test.ts
According to the old type definitions, this was correct usage:
```js
// CJS
const MockAdapter = require('axios-mock-adapter');
const mock = new MockAdapter.default(/* … */)
```
```js
// ESM
import MockAdapter from 'axios-mock-adapter';
const mock = new MockAdapter.default(/* … */)
```
With the updated type definitions, this is:
```js
// CJS
const MockAdapter = require('axios-mock-adapter');
const mock = new MockAdapter(/* … */)
```
```js
// ESM
import MockAdapter from 'axios-mock-adapter';
const mock = new MockAdapter(/* … */)
```
This has always been an issue, but it has become more apparent with the `"module": "node16"` option introduced in TypeScript 4.7.
=> Fix type exports

types/index.d.ts
`RequestHandler` is part of the `MockAdapter` namespace, not `AxiosAdapter`.
=> Fix type error

package-lock.json, package.json, types/index.d.ts
Let’s make sure types are valid from now on. :)
Based on https://github.com/ctimmerm/axios-mock-adapter/pull/368
=> Test types

src/index.js
Fix bug where `timeout()` and `timeoutOnce()` would throw `ECONNABORTED`instead of the correct `ETIMEDOUT`, when `transitional.clarifyTimeoutError` was set to `true`.
Relevant Axios documentation:
```
// throw ETIMEDOUT error instead of generic ECONNABORTED on request timeouts
clarifyTimeoutError: false,
```
Source https://github.com/axios/axios/blob/v1.x/README.md#request-config.
Closes https://github.com/ctimmerm/axios-mock-adapter/issues/336.
=> Throw ETIMEDOUT on timeout when clarifyTimeoutError is true

.github/workflows/node.js.yml
- Drop node versions lower than v18
=> Drop node versions lower than v18

types/index.d.ts, types/test.ts
- 🚧 Fix types for `mock.onGet(url).withDelayInMs(delay).reply(code, data)`
=> Fix types for withDelayInMs

README.md, src/handle_request.js, src/index.js, src/utils.js, test/basics.spec.js, test/on_any.spec.js, test/utils.spec.js, types/index.d.ts, types/test.ts
- Change the parameters of the methods to align it to the one of axios.
The last parameter must be a config object with `{params, headers}` instead of just the headers.
If you've always only used two parameters, you won't have to change anything.
Methods with data param:
- `mock.onPost(url, data, headers)` > `mock.onPost(url, data, {params, headers})`
- `mock.onPut(url, data, headers)` > `mock.onPost(url, data, {params, headers})`
- `mock.onPatch(url, data, headers)` > `mock.onPatch(url, data, {params, headers})`
- `mock.onAny(url, data, headers)` > `mock.onAny(url, {data, params, headers})`
Methods without data param:
- `mock.onGet(url, {params}, headers)` > `mock.onGet(url, {params, headers})`
- `mock.onDelete(url, {params}, headers)` > `mock.onDelete(url, {params, headers})`
- …
=> Fix params comparisons for post and put requests - Breaking Change

README.md
```javascript
import MockAdapter from 'axios-mock-adapter'
```
works too, but `AxiosMockAdapter` is a preferred term.
=> doc: Use AxiosMockAdapter throughout README
